### ISSUE TITLE
FTP Not connecting

### ISSUE THREAD

**Issue by kobadg** [mkloubert/vscode-remote-workspace#107]
After being forced to use FTP since SFTP doesn't work currently... (See previous issues from others.) I have to take a look at using FTP... However I get the following when I try to use FTP on a remote workspace.

```
[2019-02-15 08:59:06.845] [renderer3] [error] write after end: Error [ERR_STREAM_WRITE_AFTER_END]: write after end
    at writeAfterEnd (_stream_writable.js:243:12)
    at Socket.Writable.write (_stream_writable.js:291:5)
    at Stream.method [as write] (C:\Users\kbadgley\.vscode\extensions\mkloubert.vscode-remote-workspace-0.41.0\node_modules\duplexer\index.js:47:39)
    at Ftp.send (C:\Users\kbadgley\.vscode\extensions\mkloubert.vscode-remote-workspace-0.41.0\node_modules\jsftp\lib\jsftp.js:160:17)
    at Ftp.nextCmd (C:\Users\kbadgley\.vscode\extensions\mkloubert.vscode-remote-workspace-0.41.0\node_modules\jsftp\lib\jsftp.js:168:10)
    at Ftp.parse (C:\Users\kbadgley\.vscode\extensions\mkloubert.vscode-remote-workspace-0.41.0\node_modules\jsftp\lib\jsftp.js:229:8)
    at Ftp.parseResponse (C:\Users\kbadgley\.vscode\extensions\mkloubert.vscode-remote-workspace-0.41.0\node_modules\jsftp\lib\jsftp.js:146:8)
    at Stream.Ftp._createSocket.pipeline.on.data (C:\Users\kbadgley\.vscode\extensions\mkloubert.vscode-remote-workspace-0.41.0\node_modules\jsftp\lib\jsftp.js:112:10)
    at Stream.emit (events.js:182:13)
    at Stream.EventEmitter.emit (domain.js:442:20)
    at ResponseParser.reemit (C:\Users\kbadgley\.vscode\extensions\mkloubert.vscode-remote-workspace-0.41.0\node_modules\duplexer\index.js:70:25)
    at ResponseParser.emit (events.js:182:13)
    at ResponseParser.EventEmitter.emit (domain.js:442:20)
    at readableAddChunk (C:\Users\kbadgley\.vscode\extensions\mkloubert.vscode-remote-workspace-0.41.0\node_modules\ftp-response-parser\node_modules\readable-stream\lib\_stream_readable.js:195:16)
    at ResponseParser.Readable.push (C:\Users\kbadgley\.vscode\extensions\mkloubert.vscode-remote-workspace-0.41.0\node_modules\ftp-response-parser\node_modules\readable-stream\lib\_stream_readable.js:162:10)
    at ResponseParser.Transform.push (C:\Users\kbadgley\.vscode\extensions\mkloubert.vscode-remote-workspace-0.41.0\node_modules\ftp-response-parser\node_modules\readable-stream\lib\_stream_transform.js:145:32)
    at ResponseParser.<anonymous> (C:\Users\kbadgley\.vscode\extensions\mkloubert.vscode-remote-workspace-0.41.0\node_modules\ftp-response-parser\index.js:62:12)
    at Array.forEach (<anonymous>)
    at ResponseParser._transform (C:\Users\kbadgley\.vscode\extensions\mkloubert.vscode-remote-workspace-0.41.0\node_modules\ftp-response-parser\index.js:45:9)
    at ResponseParser.Transform._read (C:\Users\kbadgley\.vscode\extensions\mkloubert.vscode-remote-workspace-0.41.0\node_modules\ftp-response-parser\node_modules\readable-stream\lib\_stream_transform.js:184:10)
    at ResponseParser.Transform._write (C:\Users\kbadgley\.vscode\extensions\mkloubert.vscode-remote-workspace-0.41.0\node_modules\ftp-response-parser\node_modules\readable-stream\lib\_stream_transform.js:172:12)
    at doWrite (C:\Users\kbadgley\.vscode\extensions\mkloubert.vscode-remote-workspace-0.41.0\node_modules\ftp-response-parser\node_modules\readable-stream\lib\_stream_writable.js:279:12)
    at writeOrBuffer (C:\Users\kbadgley\.vscode\extensions\mkloubert.vscode-remote-workspace-0.41.0\node_modules\ftp-response-parser\node_modules\readable-stream\lib\_stream_writable.js:266:5)
    at ResponseParser.Writable.write (C:\Users\kbadgley\.vscode\extensions\mkloubert.vscode-remote-workspace-0.41.0\node_modules\ftp-response-parser\node_modules\readable-stream\lib\_stream_writable.js:211:11)
    at Socket.ondata (_stream_readable.js:672:20)
    at Socket.emit (events.js:182:13)
    at Socket.EventEmitter.emit (domain.js:442:20)
    at addChunk (_stream_readable.js:279:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at TCP.onread (net.js:636:20)
[2019-02-15 08:59:06.854] [renderer3] [error] write after end: Error: write after end
    at writeAfterEnd (C:\Users\kbadgley\.vscode\extensions\mkloubert.vscode-remote-workspace-0.41.0\node_modules\ftp-response-parser\node_modules\readable-stream\lib\_stream_writable.js:161:12)
    at ResponseParser.Writable.write (C:\Users\kbadgley\.vscode\extensions\mkloubert.vscode-remote-workspace-0.41.0\node_modules\ftp-response-parser\node_modules\readable-stream\lib\_stream_writable.js:208:5)
    at Socket.ondata (_stream_readable.js:672:20)
    at Socket.emit (events.js:182:13)
    at Socket.EventEmitter.emit (domain.js:442:20)
    at addChunk (_stream_readable.js:279:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at TCP.onread (net.js:636:20)
```

This results in an infinite loop, of trying to connect. Is this something stupid simple to solve or am I having something not setup correct on my end??

**Comment by kobadg** [comment]
Issue resolved.... for now.. (Till SSH/SFTP works again..)

Turns out if you don't have the FTP setup to allow from outside the home directory...ISSUES HAPPEN. (My Bad.)
