### ISSUE TITLE
Cannot connect via SFTP with a key file.

### ISSUE THREAD

**Issue by hilyin** [mkloubert/vscode-remote-workspace#21]
No matter what settings I attempt, such as:

```
{
    "folders": [{
        "uri": "sftp://user@127.0.0.1",
        "name": "Name"
    }],
    "settings": {
        "debug": 1,
	"key": "C:\\Users\\username\\Documents\\ssh\\id_rsa",
        "noPhraseFile": 1,
        "phrase": "passphrase"
    }
}
```

I always get:

```
TRACE fs.sftp.sftpfilesystem.forconnection() - [19/Jun/2018:05:27:29 +0000] "(Error) All configured authentication methods failed

Stack:
	at vscode_helpers.createLogger (C:\Users\username\.vscode\extensions\mkloubert.vscode-remote-workspace-0.27.0\out\extension.js:128:64)
	at ActionLogger.<anonymous> (C:\Users\username\.vscode\extensions\mkloubert.vscode-remote-workspace-0.27.0\node_modules\vscode-helpers\lib\logging\index.js:244:25)
	at Generator.next (<anonymous>)
	at C:\Users\username\.vscode\extensions\mkloubert.vscode-remote-workspace-0.27.0\node_modules\vscode-helpers\lib\logging\index.js:23:71
	at Promise (<anonymous>)
	at __awaiter (C:\Users\username\.vscode\extensions\mkloubert.vscode-remote-workspace-0.27.0\node_modules\vscode-helpers\lib\logging\index.js:19:12)
	at ActionLogger.onLog (C:\Users\username\.vscode\extensions\mkloubert.vscode-remote-workspace-0.27.0\node_modules\vscode-helpers\lib\logging\index.js:226:16)
	at ActionLogger.<anonymous> (C:\Users\username\.vscode\extensions\mkloubert.vscode-remote-workspace-0.27.0\node_modules\vscode-helpers\lib\logging\index.js:109:95)
	at Generator.next (<anonymous>)
	at C:\Users\username\.vscode\extensions\mkloubert.vscode-remote-workspace-0.27.0\node_modules\vscode-helpers\lib\logging\index.js:23:71
	at Promise (<anonymous>)
	at __awaiter (C:\Users\username\.vscode\extensions\mkloubert.vscode-remote-workspace-0.27.0\node_modules\vscode-helpers\lib\logging\index.js:19:12)
	at ActionLogger.log (C:\Users\username\.vscode\extensions\mkloubert.vscode-remote-workspace-0.27.0\node_modules\vscode-helpers\lib\logging\index.js:102:16)
	at ActionLogger.logSync (C:\Users\username\.vscode\extensions\mkloubert.vscode-remote-workspace-0.27.0\node_modules\vscode-helpers\lib\logging\index.js:123:14)
	at ActionLogger.trace (C:\Users\username\.vscode\extensions\mkloubert.vscode-remote-workspace-0.27.0\node_modules\vscode-helpers\lib\logging\index.js:146:21)
	at SFTPFileSystem.<anonymous> (C:\Users\username\.vscode\extensions\mkloubert.vscode-remote-workspace-0.27.0\out\fs\sftp.js:135:22)
	at Generator.throw (<anonymous>)
	at rejected (C:\Users\username\.vscode\extensions\mkloubert.vscode-remote-workspace-0.27.0\out\fs\sftp.js:21:65)
	at <anonymous>"
```

**Comment by mkloubert** [comment]
@hilyin 

The parameters are for the URI, not for the settings:

```json
{
    "folders": [{
        "uri": "sftp://user@127.0.0.1?debug=1&noPhraseFile=1&phrase=passphrase&key=C%3A%5C%5CUsers%5C%5Cusername%5C%5CDocuments%5C%5Cssh%5C%5Cid_rsa",
        "name": "Name"
    }]
}
```

I have encoded the key path by using [this web tool](https://meyerweb.com/eric/tools/dencoder/).

You also can copy the file to `C:\Users\username` and set `key` to `id_rsa` instead.

**Comment by hilyin** [comment]
@mkloubert  thanks! got it to work.
