### ISSUE TITLE
WebDav Not Using User Credential

### ISSUE THREAD

**Issue by weikai** [mkloubert/vscode-remote-workspace#36]
The user id and password is in the workspace file but it's not used to make connection.

TRACE fs.webdav.webdavfilesystem.forconnection() - [22/Jul/2018:05:20:16 +0000] "(Error) HTTP error : 401 - Unauthorized

Stack:
	at vscode_helpers.createLogger (/Users/weikai/.vscode/extensions/mkloubert.vscode-remote-workspace-0.31.0/out/extension.js:129:64)
	at ActionLogger.<anonymous> (/Users/weikai/.vscode/extensions/mkloubert.vscode-remote-workspace-0.31.0/node_modules/vscode-helpers/lib/logging/index.js:244:25)
	at Generator.next (<anonymous>)
	at /Users/weikai/.vscode/extensions/mkloubert.vscode-remote-workspace-0.31.0/node_modules/vscode-helpers/lib/logging/index.js:23:71
	at Promise (<anonymous>)
	at __awaiter (/Users/weikai/.vscode/extensions/mkloubert.vscode-remote-workspace-0.31.0/node_modules/vscode-helpers/lib/logging/index.js:19:12)
	at ActionLogger.onLog (/Users/weikai/.vscode/extensions/mkloubert.vscode-remote-workspace-0.31.0/node_modules/vscode-helpers/lib/logging/index.js:226:16)
	at ActionLogger.<anonymous> (/Users/weikai/.vscode/extensions/mkloubert.vscode-remote-workspace-0.31.0/node_modules/vscode-helpers/lib/logging/index.js:109:95)
	at Generator.next (<anonymous>)
	at /Users/weikai/.vscode/extensions/mkloubert.vscode-remote-workspace-0.31.0/node_modules/vscode-helpers/lib/logging/index.js:23:71
	at Promise (<anonymous>)
	at __awaiter (/Users/weikai/.vscode/extensions/mkloubert.vscode-remote-workspace-0.31.0/node_modules/vscode-helpers/lib/logging/index.js:19:12)
	at ActionLogger.log (/Users/weikai/.vscode/extensions/mkloubert.vscode-remote-workspace-0.31.0/node_modules/vscode-helpers/lib/logging/index.js:102:16)
	at ActionLogger.logSync (/Users/weikai/.vscode/extensions/mkloubert.vscode-remote-workspace-0.31.0/node_modules/vscode-helpers/lib/logging/index.js:123:14)
	at ActionLogger.trace (/Users/weikai/.vscode/extensions/mkloubert.vscode-remote-workspace-0.31.0/node_modules/vscode-helpers/lib/logging/index.js:146:21)
	at WebDAVFileSystem.<anonymous> (/Users/weikai/.vscode/extensions/mkloubert.vscode-remote-workspace-0.31.0/out/fs/webdav.js:109:22)
	at Generator.throw (<anonymous>)
	at rejected (/Users/weikai/.vscode/extensions/mkloubert.vscode-remote-workspace-0.31.0/out/fs/webdav.js:21:65)
	at <anonymous>
	at process._tickDomainCallback (internal/process/next_tick.js:135:7)"

**Comment by mkloubert** [comment]
@weikai 

Can you post an example URI here?

Does your WebDAV server support basic auth?

**Comment by weikai** [comment]
Here's the workspace config.  My server is using digest auth.  I've updated a development server to test out both basic and digest auth.  I've also updated the server to test HTTPS and non HTTPS.  Server settings without authentication work very well but failed to work when turning on either basic auth or digest auth.

{
    "folders": [
      {        
        "uri": "webdav://userid:password@webdav7.drupalme.net?ssl=1&debug=1",
        "name": "Drupal Sites"
      }    
    ]
}

**Comment by weikai** [comment]
Wow!  Nice job!!!  The authentication is working good now but I can only see the files not folders.  Any clue on what could be wrong?

**Comment by mkloubert** [comment]
@weikai 

Seems to be a server issue. What software for WebDAV access do you use?

**Comment by weikai** [comment]
Apache2 is installed on the host and setup as reverse proxy to forward the HTTPS requests to another Apache server with WebDav setup in the Virtualbox.  Webdav access with Windows file explorer and mounting are working fine.

**Comment by weikai** [comment]
I'm testing the connection directly with no reverse proxy in the middle.  Whenever I added the "Require valid-user" line to turn on the authentication the file directories are missing from the list.  Turning off authentication, will make the directories showing up.  

Here's my server configruation

`DavLockDB /var/www/.DavLock
<VirtualHost *:80>
        ServerName webdav7.drupalme.net
        ServerAlias Webdav7.drupalme.local
        ServerAdmin webmaster@localhost
        DocumentRoot /var/www
        <Directory /var/www>
                Options +Indexes
                IndexOptions FancyIndexing
                AddDefaultCharset UTF-8
                AllowOverride none
                #Require all granted
                #DirectoryIndex disabled
                RemoveHandler .php

                AuthType Digest
                AuthName "WebDav"
                AuthDigestProvider file
                AuthUserFile /etc/apache2/misc/.htpasswd
                Require valid-user

                DAV On
        </Directory>


        # Available loglevels: trace8, ..., trace1, debug, info, notice, warn,
        # error, crit, alert, emerg.
        # It is also possible to configure the loglevel for particular
        # modules, e.g.
        #LogLevel info ssl:warn

        ErrorLog ${APACHE_LOG_DIR}/error.log
        CustomLog ${APACHE_LOG_DIR}/access.log combined

</VirtualHost>
`

**Comment by weikai** [comment]
@mkloubert 

The problem is related to PROPFIND handling in authenticated sessions.  If I protect everything except PROPFIND it will list the directories.  I think it's a security risk to leave PROPFIND unprotected.  Is there something can be fixed in the extension?


DavLockDB /var/www/.DavLock
<VirtualHost *:80>
        ServerName webdav7.drupalme.net
        ServerAlias Webdav7.drupalme.local

        DocumentRoot /var/www
        <Directory /var/www>
                Options +Indexes
                IndexOptions FancyIndexing
                AddDefaultCharset UTF-8
                AllowOverride none
                #Require all granted
                DirectoryIndex disabled
                RemoveHandler .php



                AuthType Digest
                AuthName "WebDav"
                AuthDigestProvider file
                AuthUserFile /etc/apache2/misc/.htpasswd

                <LimitExcept PROPFIND>
                Require valid-user
                </LimitExcept>

                DAV On
        </Directory>


        # Available loglevels: trace8, ..., trace1, debug, info, notice, warn,
        # error, crit, alert, emerg.
        # It is also possible to configure the loglevel for particular
        # modules, e.g.
        #LogLevel info ssl:warn

        ErrorLog ${APACHE_LOG_DIR}/error.log
        CustomLog ${APACHE_LOG_DIR}/access.log combined

</VirtualHost>
