### ISSUE TITLE
SFTP, multiple folders on the same server

### ISSUE THREAD

**Issue by White-Owl** [mkloubert/vscode-remote-workspace#70]
I have several projects which I work simultaneously.
All of them are stored on a remote machine in tree structure like:
/MyDepartment/MyGroup/PrjA/v1.3/dev/src
/MyDepartment/MyGroup/PrjB/v2.7/dev/src
/MyDepartment/MyGroup/PrjC/v1.4/dev/src
... etc
If I define multiple workspaces, one for each project - everything is fine. But if I try to group them by server, and define 'host.code-workspace' like that:
```
{
  "folders": [
     {"name": "PrjA", "uri": "sftp://me:pass@host/MyDepartment/MyGroup/PrjA/v1.3/dev/src"},
     {"name": "PrjB", "uri": "sftp://me:pass@host/MyDepartment/MyGroup/PrjB/v2.7/dev/src"},
     {"name": "PrjC", "uri": "sftp://me:pass@host/MyDepartment/MyGroup/PrjC/v1.4/dev/src"}
  ]
}
```
I am getting a lot of errors and usually the VSCode just cannot open these folders. I am guessing it is due to a multiple actual connections, but...
Maybe it would be nice to do something like:

```
{
  "servers: [
    {"name": "dev", "uri": "sftp://me:pass@host"}
  ]
  "folders": [
     {"name": "PrjA", "server": "dev", "dir": "/MyDepartment/MyGroup/PrjA/v1.3/dev/src"},
     {"name": "PrjB", "server": "dev", "dir": "/MyDepartment/MyGroup/PrjB/v2.7/dev/src"},
     {"name": "PrjC", "server": "dev", "dir": "/MyDepartment/MyGroup/PrjC/v1.4/dev/src"}
  ]
}
```
And do it through one connections (with a lot of `cd` commands)?

**Comment by White-Owl** [comment]
It looks like the real issue is with how busy the client machine is. Today I tried to open the workspace with three connections right after rebooting my machine and although it took some time - all three connections were established and worked correctly.
In the log I see several hundred of lines like: 
```
INFO sftp://myhost:22 - [22/Oct/2018:13:16:41 +0000] "DEBUG: Local ident: 'SSH-2.0-ssh2js0.1.20'"
INFO sftp://myhost:22 - [22/Oct/2018:13:16:41 +0000] "DEBUG: Client: Trying myhost on port 22 ..."
INFO sftp://myhost:22 - [22/Oct/2018:13:16:41 +0000] "DEBUG: Local ident: 'SSH-2.0-ssh2js0.1.20'"
INFO sftp://myhost:22 - [22/Oct/2018:13:16:41 +0000] "DEBUG: Client: Trying myhost on port 22 ..."
INFO sftp://myhost:22 - [22/Oct/2018:13:16:41 +0000] "DEBUG: Local ident: 'SSH-2.0-ssh2js0.1.20'"
INFO sftp://myhost:22 - [22/Oct/2018:13:16:41 +0000] "DEBUG: Client: Trying myhost on port 22 ..."
INFO sftp://myhost:22 - [22/Oct/2018:13:16:41 +0000] "DEBUG: Local ident: 'SSH-2.0-ssh2js0.1.20'"
INFO sftp://myhost:22 - [22/Oct/2018:13:16:41 +0000] "DEBUG: Client: Trying myhost on port 22 ..."
INFO sftp://myhost:22 - [22/Oct/2018:13:16:41 +0000] "DEBUG: Local ident: 'SSH-2.0-ssh2js0.1.20'"
INFO sftp://myhost:22 - [22/Oct/2018:13:16:41 +0000] "DEBUG: Client: Trying myhost on port 22 ..."
INFO sftp://myhost:22 - [22/Oct/2018:13:16:41 +0000] "DEBUG: Local ident: 'SSH-2.0-ssh2js0.1.20'"
INFO sftp://myhost:22 - [22/Oct/2018:13:16:41 +0000] "DEBUG: Client: Trying myhost on port 22 ..."
INFO sftp://myhost:22 - [22/Oct/2018:13:16:41 +0000] "DEBUG: Local ident: 'SSH-2.0-ssh2js0.1.20'"
INFO sftp://myhost:22 - [22/Oct/2018:13:16:41 +0000] "DEBUG: Client: Trying myhost on port 22 ..."
INFO sftp://myhost:22 - [22/Oct/2018:13:16:41 +0000] "DEBUG: Local ident: 'SSH-2.0-ssh2js0.1.20'"
INFO sftp://myhost:22 - [22/Oct/2018:13:16:41 +0000] "DEBUG: Client: Trying myhost on port 22 ..."
INFO sftp://myhost:22 - [22/Oct/2018:13:16:41 +0000] "DEBUG: Local ident: 'SSH-2.0-ssh2js0.1.20'"
INFO sftp://myhost:22 - [22/Oct/2018:13:16:41 +0000] "DEBUG: Client: Trying myhost on port 22 ..."
INFO sftp://myhost:22 - [22/Oct/2018:13:16:41 +0000] "DEBUG: Local ident: 'SSH-2.0-ssh2js0.1.20'"
```

Then I eighteen (I have just three connections requested???) lines: 

```
INFO sftp://myhost:22 - [22/Oct/2018:13:16:41 +0000] "DEBUG: Client: Connected"
INFO sftp://myhost:22 - [22/Oct/2018:13:16:41 +0000] "DEBUG: Client: Connected"
INFO sftp://myhost:22 - [22/Oct/2018:13:16:41 +0000] "DEBUG: Client: Connected"
INFO sftp://myhost:22 - [22/Oct/2018:13:16:41 +0000] "DEBUG: Client: Connected"
INFO sftp://myhost:22 - [22/Oct/2018:13:16:41 +0000] "DEBUG: Client: Connected"

```

After that, I see twenty attempts to exchange ssh keys.  And then finally there are normal SFTP commands, but all of them many times multiplied.

**Comment by White-Owl** [comment]
It looks like the issue is how busy the client machine and network are.
First thing in the morning with almost no one in the office, on freshly rebooted computer and after several minutes of waiting got a working connections to all three folders of the remote machine. In the log, I see each command repeated multiple times. First I have several hundred of lines:
```
INFO sftp://myhost:22 - [22/Oct/2018:13:49:44 +0000] "DEBUG: Local ident: 'SSH-2.0-ssh2js0.1.20'"
INFO sftp://myhost:22 - [22/Oct/2018:13:49:44 +0000] "DEBUG: Client: Trying myhost on port 22 ..."
```
Then a few dozen of lines:
```
INFO sftp://myhost:22 - [22/Oct/2018:13:49:44 +0000] "DEBUG: Client: Connected"
```
Then several attempts to exchange SSH keys... And then each command repeated several times without a single error in between.


After an hour in the work day, I was not able to open the very same three-connection workspace at all.

And finally it started to throw out messages:
```
TRACE fs.sftp.sftpfilesystem.forconnection() - [22/Oct/2018:13:49:49 +0000] "(EntryNotFound (FileSystemError)) sftp://user:password@myhost/ms/dev/testco/CICS_Abend/dev/src/.vscode?debug=1

Stack:
	at vscode_helpers.createLogger (C:\Users\user\.vscode\extensions\mkloubert.vscode-remote-workspace-0.35.1\out\extension.js:131:64)
	at ActionLogger.<anonymous> (C:\Users\user\.vscode\extensions\mkloubert.vscode-remote-workspace-0.35.1\node_modules\vscode-helpers\lib\logging\index.js:244:25)
	at Generator.next (<anonymous>)
	at C:\Users\user\.vscode\extensions\mkloubert.vscode-remote-workspace-0.35.1\node_modules\vscode-helpers\lib\logging\index.js:23:71
	at new Promise (<anonymous>)
	at __awaiter (C:\Users\user\.vscode\extensions\mkloubert.vscode-remote-workspace-0.35.1\node_modules\vscode-helpers\lib\logging\index.js:19:12)
	at ActionLogger.onLog (C:\Users\user\.vscode\extensions\mkloubert.vscode-remote-workspace-0.35.1\node_modules\vscode-helpers\lib\logging\index.js:226:16)
	at ActionLogger.<anonymous> (C:\Users\user\.vscode\extensions\mkloubert.vscode-remote-workspace-0.35.1\node_modules\vscode-helpers\lib\logging\index.js:109:95)
	at Generator.next (<anonymous>)
	at C:\Users\user\.vscode\extensions\mkloubert.vscode-remote-workspace-0.35.1\node_modules\vscode-helpers\lib\logging\index.js:23:71
	at new Promise (<anonymous>)
	at __awaiter (C:\Users\user\.vscode\extensions\mkloubert.vscode-remote-workspace-0.35.1\node_modules\vscode-helpers\lib\logging\index.js:19:12)
	at ActionLogger.log (C:\Users\user\.vscode\extensions\mkloubert.vscode-remote-workspace-0.35.1\node_modules\vscode-helpers\lib\logging\index.js:102:16)
	at ActionLogger.logSync (C:\Users\user\.vscode\extensions\mkloubert.vscode-remote-workspace-0.35.1\node_modules\vscode-helpers\lib\logging\index.js:123:14)
	at ActionLogger.trace (C:\Users\user\.vscode\extensions\mkloubert.vscode-remote-workspace-0.35.1\node_modules\vscode-helpers\lib\logging\index.js:146:21)
	at SFTPFileSystem.<anonymous> (C:\Users\user\.vscode\extensions\mkloubert.vscode-remote-workspace-0.35.1\out\fs\sftp.js:143:22)
	at Generator.throw (<anonymous>)
	at rejected (C:\Users\user\.vscode\extensions\mkloubert.vscode-remote-workspace-0.35.1\out\fs\sftp.js:21:65)
	at <anonymous>"
```
