### ISSUE TITLE
getting 404 from S3

### ISSUE THREAD

**Issue by edt82** [mkloubert/vscode-remote-workspace#72]
Extension version: 035.1
VSCode details:
```
Version: 1.28.2 (user setup)
Commit: 7f3ce96ff4729c91352ae6def877e59c561f4850
Date: 2018-10-17T00:23:51.859Z
Electron: 2.0.9
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64
OS: Windows 10 (Build 17134.345)

```
.code-workspace:
```
{
	"folders": [{
            "uri": "s3://shared@techphlex-greengrass/?profile=blue&debug=1",
            "name": "s3"
        }]
}
```
Log file (why the single debug line per char?):
```
INFO s3 - [21/Oct/2018:05:14:02 +0000] "["
INFO s3 - [21/Oct/2018:05:14:02 +0000] "A"
INFO s3 - [21/Oct/2018:05:14:02 +0000] "W"
INFO s3 - [21/Oct/2018:05:14:02 +0000] "S"
INFO s3 - [21/Oct/2018:05:14:02 +0000] " "
INFO s3 - [21/Oct/2018:05:14:02 +0000] "s"
INFO s3 - [21/Oct/2018:05:14:02 +0000] "3"
INFO s3 - [21/Oct/2018:05:14:02 +0000] " "
INFO s3 - [21/Oct/2018:05:14:02 +0000] "4"
INFO s3 - [21/Oct/2018:05:14:02 +0000] "0"
INFO s3 - [21/Oct/2018:05:14:03 +0000] "4"
INFO s3 - [21/Oct/2018:05:14:03 +0000] " "
INFO s3 - [21/Oct/2018:05:14:03 +0000] "8"
INFO s3 - [21/Oct/2018:05:14:03 +0000] "."
INFO s3 - [21/Oct/2018:05:14:03 +0000] "9"
INFO s3 - [21/Oct/2018:05:14:03 +0000] "5"
INFO s3 - [21/Oct/2018:05:14:03 +0000] "7"
INFO s3 - [21/Oct/2018:05:14:03 +0000] "s"
INFO s3 - [21/Oct/2018:05:14:03 +0000] " "
INFO s3 - [21/Oct/2018:05:14:03 +0000] "0"
INFO s3 - [21/Oct/2018:05:14:03 +0000] " "
INFO s3 - [21/Oct/2018:05:14:03 +0000] "r"
INFO s3 - [21/Oct/2018:05:14:03 +0000] "e"
INFO s3 - [21/Oct/2018:05:14:03 +0000] "t"
INFO s3 - [21/Oct/2018:05:14:03 +0000] "r"
INFO s3 - [21/Oct/2018:05:14:03 +0000] "i"
INFO s3 - [21/Oct/2018:05:14:03 +0000] "e"
INFO s3 - [21/Oct/2018:05:14:03 +0000] "s"
INFO s3 - [21/Oct/2018:05:14:03 +0000] "]"
INFO s3 - [21/Oct/2018:05:14:03 +0000] " "
INFO s3 - [21/Oct/2018:05:14:03 +0000] "g"
INFO s3 - [21/Oct/2018:05:14:03 +0000] "e"
INFO s3 - [21/Oct/2018:05:14:03 +0000] "t"
INFO s3 - [21/Oct/2018:05:14:03 +0000] "O"
INFO s3 - [21/Oct/2018:05:14:03 +0000] "b"
INFO s3 - [21/Oct/2018:05:14:03 +0000] "j"
INFO s3 - [21/Oct/2018:05:14:03 +0000] "e"
INFO s3 - [21/Oct/2018:05:14:03 +0000] "c"
INFO s3 - [21/Oct/2018:05:14:03 +0000] "t"
INFO s3 - [21/Oct/2018:05:14:03 +0000] "("
INFO s3 - [21/Oct/2018:05:14:03 +0000] "{"
INFO s3 - [21/Oct/2018:05:14:03 +0000] " "
INFO s3 - [21/Oct/2018:05:14:03 +0000] "B"
INFO s3 - [21/Oct/2018:05:14:03 +0000] "u"
INFO s3 - [21/Oct/2018:05:14:03 +0000] "c"
INFO s3 - [21/Oct/2018:05:14:03 +0000] "k"
INFO s3 - [21/Oct/2018:05:14:03 +0000] "e"
INFO s3 - [21/Oct/2018:05:14:03 +0000] "t"
INFO s3 - [21/Oct/2018:05:14:03 +0000] ":"
INFO s3 - [21/Oct/2018:05:14:03 +0000] " "
INFO s3 - [21/Oct/2018:05:14:03 +0000] "'"
INFO s3 - [21/Oct/2018:05:14:03 +0000] "t"
INFO s3 - [21/Oct/2018:05:14:03 +0000] "e"
INFO s3 - [21/Oct/2018:05:14:03 +0000] "c"
INFO s3 - [21/Oct/2018:05:14:03 +0000] "h"
INFO s3 - [21/Oct/2018:05:14:03 +0000] "p"
INFO s3 - [21/Oct/2018:05:14:03 +0000] "h"
INFO s3 - [21/Oct/2018:05:14:03 +0000] "l"
INFO s3 - [21/Oct/2018:05:14:03 +0000] "e"
INFO s3 - [21/Oct/2018:05:14:03 +0000] "x"
INFO s3 - [21/Oct/2018:05:14:03 +0000] "-"
INFO s3 - [21/Oct/2018:05:14:03 +0000] "g"
INFO s3 - [21/Oct/2018:05:14:03 +0000] "r"
INFO s3 - [21/Oct/2018:05:14:03 +0000] "e"
INFO s3 - [21/Oct/2018:05:14:03 +0000] "e"
INFO s3 - [21/Oct/2018:05:14:03 +0000] "n"
INFO s3 - [21/Oct/2018:05:14:03 +0000] "g"
INFO s3 - [21/Oct/2018:05:14:04 +0000] "r"
INFO s3 - [21/Oct/2018:05:14:04 +0000] "a"
INFO s3 - [21/Oct/2018:05:14:04 +0000] "s"
INFO s3 - [21/Oct/2018:05:14:04 +0000] "s"
INFO s3 - [21/Oct/2018:05:14:04 +0000] "'"
INFO s3 - [21/Oct/2018:05:14:04 +0000] ","
INFO s3 - [21/Oct/2018:05:14:04 +0000] " "
INFO s3 - [21/Oct/2018:05:14:04 +0000] "K"
INFO s3 - [21/Oct/2018:05:14:04 +0000] "e"
INFO s3 - [21/Oct/2018:05:14:04 +0000] "y"
INFO s3 - [21/Oct/2018:05:14:04 +0000] ":"
INFO s3 - [21/Oct/2018:05:14:04 +0000] " "
INFO s3 - [21/Oct/2018:05:14:04 +0000] "'"
INFO s3 - [21/Oct/2018:05:14:04 +0000] "."
INFO s3 - [21/Oct/2018:05:14:04 +0000] "v"
INFO s3 - [21/Oct/2018:05:14:04 +0000] "s"
INFO s3 - [21/Oct/2018:05:14:04 +0000] "c"
INFO s3 - [21/Oct/2018:05:14:04 +0000] "o"
INFO s3 - [21/Oct/2018:05:14:04 +0000] "d"
INFO s3 - [21/Oct/2018:05:14:04 +0000] "e"
INFO s3 - [21/Oct/2018:05:14:04 +0000] "/"
INFO s3 - [21/Oct/2018:05:14:04 +0000] "'"
INFO s3 - [21/Oct/2018:05:14:04 +0000] " "
INFO s3 - [21/Oct/2018:05:14:04 +0000] "}"
INFO s3 - [21/Oct/2018:05:14:04 +0000] ")"
TRACE fs.s3.s3filesystem.forconnection() - [21/Oct/2018:05:14:04 +0000] "(NoSuchKey) The specified key does not exist.

Stack:
	at vscode_helpers.createLogger (C:\Users\blue\.vscode\extensions\mkloubert.vscode-remote-workspace-0.35.1\out\extension.js:131:64)
	at ActionLogger.<anonymous> (C:\Users\blue\.vscode\extensions\mkloubert.vscode-remote-workspace-0.35.1\node_modules\vscode-helpers\lib\logging\index.js:244:25)
	at Generator.next (<anonymous>)
	at C:\Users\blue\.vscode\extensions\mkloubert.vscode-remote-workspace-0.35.1\node_modules\vscode-helpers\lib\logging\index.js:23:71
	at new Promise (<anonymous>)
	at __awaiter (C:\Users\blue\.vscode\extensions\mkloubert.vscode-remote-workspace-0.35.1\node_modules\vscode-helpers\lib\logging\index.js:19:12)
	at ActionLogger.onLog (C:\Users\blue\.vscode\extensions\mkloubert.vscode-remote-workspace-0.35.1\node_modules\vscode-helpers\lib\logging\index.js:226:16)
	at ActionLogger.<anonymous> (C:\Users\blue\.vscode\extensions\mkloubert.vscode-remote-workspace-0.35.1\node_modules\vscode-helpers\lib\logging\index.js:109:95)
	at Generator.next (<anonymous>)
	at C:\Users\blue\.vscode\extensions\mkloubert.vscode-remote-workspace-0.35.1\node_modules\vscode-helpers\lib\logging\index.js:23:71
	at new Promise (<anonymous>)
	at __awaiter (C:\Users\blue\.vscode\extensions\mkloubert.vscode-remote-workspace-0.35.1\node_modules\vscode-helpers\lib\logging\index.js:19:12)
	at ActionLogger.log (C:\Users\blue\.vscode\extensions\mkloubert.vscode-remote-workspace-0.35.1\node_modules\vscode-helpers\lib\logging\index.js:102:16)
	at ActionLogger.logSync (C:\Users\blue\.vscode\extensions\mkloubert.vscode-remote-workspace-0.35.1\node_modules\vscode-helpers\lib\logging\index.js:123:14)
	at ActionLogger.trace (C:\Users\blue\.vscode\extensions\mkloubert.vscode-remote-workspace-0.35.1\node_modules\vscode-helpers\lib\logging\index.js:146:21)
	at S3FileSystem.<anonymous> (C:\Users\blue\.vscode\extensions\mkloubert.vscode-remote-workspace-0.35.1\out\fs\s3.js:133:22)
	at Generator.throw (<anonymous>)
	at rejected (C:\Users\blue\.vscode\extensions\mkloubert.vscode-remote-workspace-0.35.1\out\fs\s3.js:21:65)
	at <anonymous>
	at process._tickDomainCallback (internal/process/next_tick.js:228:7)"

```

So its looking a `.vscode` key in my bucket. What am I missing in the extension setup?

**Comment by mkloubert** [comment]
@edt82 

**Since version 0.36.2** logging messages for [S3](https://github.com/mkloubert/vscode-remote-workspace#s3-buckets-) should be fixed.

Looking for a `.vscode` "folder" is the normal behaviour of VSCode.

It also looks / requests for things like

* `.vscode/settings.json`
* `node_modules`

automatically, after you have started to connect to your bucket.
