### ISSUE TITLE
pre-existing folders aren't sync'ed

### ISSUE THREAD

**Issue by edt82** [mkloubert/vscode-remote-workspace#74]
Here's what I noticed:
- there were no files in the bucket root before using remote-workspace
- 2 folders existed (with files within them) in the S3 bucket before using remote-workspace, they are **lambda** and **feeds**
- these 2 folders aren't getting sync'ed to vscode
- have tried adding new files under the 2 original folders with no success
- creating files and folders at both ends (vscode and aws s3 console) are sync'ed as expected
- after all the above activities to create/delete/edit files and folders, the 2 pre-exisitng folders are never sync'ed to vscode. 

![image](https://user-images.githubusercontent.com/14885580/47322018-3f4f2e80-d6a2-11e8-87df-0f0945edbdca.png)

Logs:
```
INFO s3 - [22/Oct/2018:21:26:53 +0000] "[AWS s3 200 1.504s 0 retries] listObjectsV2({ Bucket: 'techphlex-greengrass',
  ContinuationToken: undefined,
  Prefix: '' })"
INFO s3 - [22/Oct/2018:21:28:02 +0000] "[AWS s3 200 1.256s 0 retries] listObjectsV2({ Bucket: 'techphlex-greengrass',
  ContinuationToken: undefined,
  Prefix: '' })"
INFO s3 - [22/Oct/2018:21:28:15 +0000] "[AWS s3 200 1.307s 0 retries] getObject({ Bucket: 'techphlex-greengrass', Key: 'requirements.txt' })"
INFO s3 - [22/Oct/2018:21:28:16 +0000] "[AWS s3 200 1.104s 0 retries] getObject({ Bucket: 'techphlex-greengrass', Key: 'requirements.txt' })"
INFO s3 - [22/Oct/2018:21:28:22 +0000] "[AWS s3 200 1.276s 0 retries] getObject({ Bucket: 'techphlex-greengrass', Key: 'requirements.txt' })"
INFO s3 - [22/Oct/2018:21:28:27 +0000] "[AWS s3 200 1.421s 0 retries] getObject({ Bucket: 'techphlex-greengrass', Key: 'requirements.txt' })"
INFO s3 - [22/Oct/2018:21:35:23 +0000] "[AWS s3 200 1.194s 0 retries] listObjectsV2({ Bucket: 'techphlex-greengrass',
  ContinuationToken: undefined,
  Prefix: '' })"
INFO s3 - [22/Oct/2018:21:35:23 +0000] "[AWS s3 404 1.346s 0 retries] getObject({ Bucket: 'techphlex-greengrass', Key: '.vscode' })"
INFO s3 - [22/Oct/2018:21:35:25 +0000] "[AWS s3 404 1.201s 0 retries] getObject({ Bucket: 'techphlex-greengrass', Key: '.vscode/' })"
TRACE fs.s3.s3filesystem.forconnection() - [22/Oct/2018:21:35:25 +0000] "(NoSuchKey) The specified key does not exist.

Stack:
	at vscode_helpers.createLogger (C:\Users\blue\.vscode\extensions\mkloubert.vscode-remote-workspace-0.36.5\out\extension.js:131:64)
	at ActionLogger.<anonymous> (C:\Users\blue\.vscode\extensions\mkloubert.vscode-remote-workspace-0.36.5\node_modules\vscode-helpers\lib\logging\index.js:244:25)
	at Generator.next (<anonymous>)
	at C:\Users\blue\.vscode\extensions\mkloubert.vscode-remote-workspace-0.36.5\node_modules\vscode-helpers\lib\logging\index.js:23:71
	at new Promise (<anonymous>)
	at __awaiter (C:\Users\blue\.vscode\extensions\mkloubert.vscode-remote-workspace-0.36.5\node_modules\vscode-helpers\lib\logging\index.js:19:12)
	at ActionLogger.onLog (C:\Users\blue\.vscode\extensions\mkloubert.vscode-remote-workspace-0.36.5\node_modules\vscode-helpers\lib\logging\index.js:226:16)
	at ActionLogger.<anonymous> (C:\Users\blue\.vscode\extensions\mkloubert.vscode-remote-workspace-0.36.5\node_modules\vscode-helpers\lib\logging\index.js:109:95)
	at Generator.next (<anonymous>)
	at C:\Users\blue\.vscode\extensions\mkloubert.vscode-remote-workspace-0.36.5\node_modules\vscode-helpers\lib\logging\index.js:23:71
	at new Promise (<anonymous>)
	at __awaiter (C:\Users\blue\.vscode\extensions\mkloubert.vscode-remote-workspace-0.36.5\node_modules\vscode-helpers\lib\logging\index.js:19:12)
	at ActionLogger.log (C:\Users\blue\.vscode\extensions\mkloubert.vscode-remote-workspace-0.36.5\node_modules\vscode-helpers\lib\logging\index.js:102:16)
	at ActionLogger.logSync (C:\Users\blue\.vscode\extensions\mkloubert.vscode-remote-workspace-0.36.5\node_modules\vscode-helpers\lib\logging\index.js:123:14)
	at ActionLogger.trace (C:\Users\blue\.vscode\extensions\mkloubert.vscode-remote-workspace-0.36.5\node_modules\vscode-helpers\lib\logging\index.js:146:21)
	at S3FileSystem.<anonymous> (C:\Users\blue\.vscode\extensions\mkloubert.vscode-remote-workspace-0.36.5\out\fs\s3.js:133:22)
	at Generator.throw (<anonymous>)
	at rejected (C:\Users\blue\.vscode\extensions\mkloubert.vscode-remote-workspace-0.36.5\out\fs\s3.js:21:65)
	at <anonymous>
	at process._tickDomainCallback (internal/process/next_tick.js:228:7)"
INFO s3 - [22/Oct/2018:21:36:14 +0000] "[AWS s3 404 1.246s 0 retries] getObject({ Bucket: 'techphlex-greengrass', Key: '.vscode' })"
INFO s3 - [22/Oct/2018:21:36:14 +0000] "[AWS s3 200 1.175s 0 retries] listObjectsV2({ Bucket: 'techphlex-greengrass',
  ContinuationToken: undefined,
  Prefix: '' })"
INFO s3 - [22/Oct/2018:21:36:15 +0000] "[AWS s3 200 1.264s 0 retries] listObjectsV2({ Bucket: 'techphlex-greengrass',
  ContinuationToken: undefined,
  Prefix: '' })"
INFO s3 - [22/Oct/2018:21:36:16 +0000] "[AWS s3 404 1.215s 0 retries] getObject({ Bucket: 'techphlex-greengrass', Key: '.vscode/' })"
TRACE fs.s3.s3filesystem.forconnection() - [22/Oct/2018:21:36:16 +0000] "(NoSuchKey) The specified key does not exist.

Stack:
	at vscode_helpers.createLogger (C:\Users\blue\.vscode\extensions\mkloubert.vscode-remote-workspace-0.36.5\out\extension.js:131:64)
	at ActionLogger.<anonymous> (C:\Users\blue\.vscode\extensions\mkloubert.vscode-remote-workspace-0.36.5\node_modules\vscode-helpers\lib\logging\index.js:244:25)
	at Generator.next (<anonymous>)
	at C:\Users\blue\.vscode\extensions\mkloubert.vscode-remote-workspace-0.36.5\node_modules\vscode-helpers\lib\logging\index.js:23:71
	at new Promise (<anonymous>)
	at __awaiter (C:\Users\blue\.vscode\extensions\mkloubert.vscode-remote-workspace-0.36.5\node_modules\vscode-helpers\lib\logging\index.js:19:12)
	at ActionLogger.onLog (C:\Users\blue\.vscode\extensions\mkloubert.vscode-remote-workspace-0.36.5\node_modules\vscode-helpers\lib\logging\index.js:226:16)
	at ActionLogger.<anonymous> (C:\Users\blue\.vscode\extensions\mkloubert.vscode-remote-workspace-0.36.5\node_modules\vscode-helpers\lib\logging\index.js:109:95)
	at Generator.next (<anonymous>)
	at C:\Users\blue\.vscode\extensions\mkloubert.vscode-remote-workspace-0.36.5\node_modules\vscode-helpers\lib\logging\index.js:23:71
	at new Promise (<anonymous>)
	at __awaiter (C:\Users\blue\.vscode\extensions\mkloubert.vscode-remote-workspace-0.36.5\node_modules\vscode-helpers\lib\logging\index.js:19:12)
	at ActionLogger.log (C:\Users\blue\.vscode\extensions\mkloubert.vscode-remote-workspace-0.36.5\node_modules\vscode-helpers\lib\logging\index.js:102:16)
	at ActionLogger.logSync (C:\Users\blue\.vscode\extensions\mkloubert.vscode-remote-workspace-0.36.5\node_modules\vscode-helpers\lib\logging\index.js:123:14)
	at ActionLogger.trace (C:\Users\blue\.vscode\extensions\mkloubert.vscode-remote-workspace-0.36.5\node_modules\vscode-helpers\lib\logging\index.js:146:21)
	at S3FileSystem.<anonymous> (C:\Users\blue\.vscode\extensions\mkloubert.vscode-remote-workspace-0.36.5\out\fs\s3.js:133:22)
	at Generator.throw (<anonymous>)
	at rejected (C:\Users\blue\.vscode\extensions\mkloubert.vscode-remote-workspace-0.36.5\out\fs\s3.js:21:65)
	at <anonymous>
	at process._tickDomainCallback (internal/process/next_tick.js:228:7)"
INFO s3 - [22/Oct/2018:21:36:57 +0000] "[AWS s3 200 1.416s 0 retries] listObjectsV2({ Bucket: 'techphlex-greengrass',
  ContinuationToken: undefined,
  Prefix: '' })"
INFO s3 - [22/Oct/2018:21:36:58 +0000] "[AWS s3 200 1.249s 0 retries] listObjectsV2({ Bucket: 'techphlex-greengrass',
  ContinuationToken: undefined,
  Prefix: '' })"
INFO s3 - [22/Oct/2018:21:39:24 +0000] "[AWS s3 404 1.496s 0 retries] getObject({ Bucket: 'techphlex-greengrass', Key: '.vscode' })"
INFO s3 - [22/Oct/2018:21:39:25 +0000] "[AWS s3 404 1.106s 0 retries] getObject({ Bucket: 'techphlex-greengrass', Key: '.vscode/' })"
TRACE fs.s3.s3filesystem.forconnection() - [22/Oct/2018:21:39:25 +0000] "(NoSuchKey) The specified key does not exist.

Stack:
	at vscode_helpers.createLogger (C:\Users\blue\.vscode\extensions\mkloubert.vscode-remote-workspace-0.36.5\out\extension.js:131:64)
	at ActionLogger.<anonymous> (C:\Users\blue\.vscode\extensions\mkloubert.vscode-remote-workspace-0.36.5\node_modules\vscode-helpers\lib\logging\index.js:244:25)
	at Generator.next (<anonymous>)
	at C:\Users\blue\.vscode\extensions\mkloubert.vscode-remote-workspace-0.36.5\node_modules\vscode-helpers\lib\logging\index.js:23:71
	at new Promise (<anonymous>)
	at __awaiter (C:\Users\blue\.vscode\extensions\mkloubert.vscode-remote-workspace-0.36.5\node_modules\vscode-helpers\lib\logging\index.js:19:12)
	at ActionLogger.onLog (C:\Users\blue\.vscode\extensions\mkloubert.vscode-remote-workspace-0.36.5\node_modules\vscode-helpers\lib\logging\index.js:226:16)
	at ActionLogger.<anonymous> (C:\Users\blue\.vscode\extensions\mkloubert.vscode-remote-workspace-0.36.5\node_modules\vscode-helpers\lib\logging\index.js:109:95)
	at Generator.next (<anonymous>)
	at C:\Users\blue\.vscode\extensions\mkloubert.vscode-remote-workspace-0.36.5\node_modules\vscode-helpers\lib\logging\index.js:23:71
	at new Promise (<anonymous>)
	at __awaiter (C:\Users\blue\.vscode\extensions\mkloubert.vscode-remote-workspace-0.36.5\node_modules\vscode-helpers\lib\logging\index.js:19:12)
	at ActionLogger.log (C:\Users\blue\.vscode\extensions\mkloubert.vscode-remote-workspace-0.36.5\node_modules\vscode-helpers\lib\logging\index.js:102:16)
	at ActionLogger.logSync (C:\Users\blue\.vscode\extensions\mkloubert.vscode-remote-workspace-0.36.5\node_modules\vscode-helpers\lib\logging\index.js:123:14)
	at ActionLogger.trace (C:\Users\blue\.vscode\extensions\mkloubert.vscode-remote-workspace-0.36.5\node_modules\vscode-helpers\lib\logging\index.js:146:21)
	at S3FileSystem.<anonymous> (C:\Users\blue\.vscode\extensions\mkloubert.vscode-remote-workspace-0.36.5\out\fs\s3.js:133:22)
	at Generator.throw (<anonymous>)
	at rejected (C:\Users\blue\.vscode\extensions\mkloubert.vscode-remote-workspace-0.36.5\out\fs\s3.js:21:65)
	at <anonymous>
	at process._tickDomainCallback (internal/process/next_tick.js:228:7)"
INFO s3 - [22/Oct/2018:21:39:32 +0000] "[AWS s3 200 2.37s 0 retries] listObjectsV2({ Bucket: 'techphlex-greengrass',
  ContinuationToken: undefined,
  Prefix: '' })"
INFO s3 - [22/Oct/2018:21:39:33 +0000] "[AWS s3 200 1.451s 0 retries] listObjectsV2({ Bucket: 'techphlex-greengrass',
  ContinuationToken: undefined,
  Prefix: '' })"

```

**Comment by ddimitrioglo** [comment]
Having the same issue:

the `test` folder was created from vscode:
![image](https://user-images.githubusercontent.com/9005667/57804310-0c19dd00-7763-11e9-817d-eb8c37ce1ff6.png)

but `stores` folder already existed in s3:
![image](https://user-images.githubusercontent.com/9005667/57804437-5307d280-7763-11e9-9f15-196a4a1a6fa3.png)

Any updates on this topic?

**Comment by ricardopieper** [comment]
I'm having the same issuel I thought it was a problem with all folders, but I just created one and it shows up.
